CREATE TABLE acao (
    id INT NOT NULL,
    nome VARCHAR(40) NOT NULL,
    descricao VARCHAR(100),
    ativo BOOLEAN NOT NULL,
    PRIMARY KEY(id)
);

CREATE SEQUENCE acao_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE TABLE execucao (
    id INT NOT NULL,
    data_exec TIMESTAMP(0) NOT NULL,
    acao_id INT NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE execucao ADD CONSTRAINT fk_acao_id FOREIGN KEY (acao_id) REFERENCES acao(id);

CREATE SEQUENCE execucao_seq INCREMENT BY 1 START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE NOCACHE;